{{- if and .Values.metrics.enabled .Values.metrics.prometheus.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "azimuth-schedule-operator.fullname" . }}
  labels: {{ include "azimuth-schedule-operator.labels" . | nindent 4 }}
spec:
  groups:
    - name: azimuth-schedule-operator.rules
      rules:
        - alert: AzimuthScheduleRefNotFound
          expr: >-
            sum(azimuth_schedule_delete_triggered{schedule_ref_found!="true"}) by(schedule_namespace, schedule_name) > 0
          for: 15m
          annotations:
            description: >-
              Azimuth schedule
              {{ "{{" }} $labels.schedule_namespace {{ "}}" }}/{{ "{{" }} $labels.schedule_name {{ "}}" }}
              has been in a not found state for longer than 15 mins.
            summary: Azimuth schedule has not found its ref for longer than 15 mins.
          labels:
            severity: warning

        - alert: AzimuthLeaseNotPendingOrActive
          expr: >-
            sum(azimuth_lease_phase{phase!~"Pending|Active"}) by(lease_namespace, lease_name) > 0
          for: 1h
          annotations:
            description: >-
              Azimuth lease
              {{ "{{" }} $labels.lease_namespace {{ "}}" }}/{{ "{{" }} $labels.lease_name {{ "}}" }}
              has been in a state other than Pending or Active for longer than one hour.
            summary: Azimuth lease has been in an unstable state for more than one hour.
          labels:
            severity: warning
{{- end }}
