{{- if and .Values.metrics.enabled .Values.metrics.prometheus.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "azimuth-schedule-operator.fullname" . }}
  labels: {{ include "azimuth-schedule-operator.labels" . | nindent 4 }}
spec:
  groups:
    - name: azimuth-schedule-operator.rules
      rules:
        - alert: AzimuthScheduleRefNotFound
          expr: >-
            sum(azimuth_schedule_delete_triggered{refFound!="True"}) by(schedule_namespace, schedule_name) > 0
          for: 15m
          annotations:
            description: >-
              Azimuth schedule
              {{ "{{" }} $labels.schedule_namespace {{ "}}" }}/{{ "{{" }} $labels.schedule_name {{ "}}" }}
              has been in a not found state for longer than 15 mins.
            summary: Azimuth schedule has not found its ref for longer than 15 mins.
          labels:
            severity: warning
{{- end }}
