---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caas-mycluster
data:
  key1: value1
  key2: value2
---
apiVersion: scheduling.azimuth.stackhpc.com/v1alpha1
kind: Schedule
metadata:
  name: caas-mycluster
  ownerReferences: []
spec:
  ref:
    apiVersion: v1
    kind: ConfigMap
    name: caas-mycluster
  notAfter: $AFTER
