---
apiVersion: scheduling.azimuth.stackhpc.com/v1alpha1
kind: Schedule
metadata:
  name: caas-mycluster
  ownerReferences: []
spec:
  ref:
    apiVersion: caas.azimuth.stackhpc.com/v1alpha1
    kind: Cluster
    name: mycluster
  notBefore: "20240302T09:00:00Z"
  notAfter: "20250302T10:00:00Z"