name: Functional tests

on:
  workflow_call:

jobs:
  functional_test:
    name: Operator functional tests
    # timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.15

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.11.3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # - name: Create k8s Kind Cluster
      #   uses: helm/kind-action@v1.10.0

      # - name: Run test
      #   timeout-minutes: 10
      #   run: tools/functional_test.sh
