name: Functional tests

on:
  workflow_call:

jobs:
  functional_test:
    name: Operator functional tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.15

      - name: Install k3s
        run: |
          set -eo pipefail
          curl -sfL https://get.k3s.io | \
          bash -s - \
            --disable traefik \
            --cluster-cidr 172.30.0.0/16 \
            --service-cidr 172.31.0.0/16
          mkdir $HOME/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
          sudo chown $USER $HOME/.kube/config

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install gomplate
        run: |
          GOBIN=/usr/local/bin \
            go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest
          gomplate --version

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run functional tests
        timeout-minutes: 15
        run: |
          source devstack/openrc demo demo
          tools/functional_test.sh
