name: Functional tests

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The ref to build.
        required: true

jobs:
  functional_test:
    name: Operator functional tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Get SemVer version for current commit
        id: semver
        uses: azimuth-cloud/github-actions/semver@master

      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.19

      - name: Install k3s
        run: |
          set -eo pipefail
          curl -sfL https://get.k3s.io | \
          bash -s - \
            --disable traefik \
            --cluster-cidr 172.30.0.0/16 \
            --service-cidr 172.31.0.0/16
          mkdir $HOME/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
          sudo chown $USER $HOME/.kube/config

      - name: Install gomplate
        run: |
          GOBIN=/usr/local/bin \
            go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest
          gomplate --version

      - name: Run functional tests
        timeout-minutes: 15
        run: |
          source devstack/openrc demo demo
          tools/functional_test.sh
        env:
          IMAGE_TAG: ${{ steps.semver.outputs.short-sha }}
