name: Functional tests

on:
  workflow_call:

jobs:
  functional_test:
    name: Operator functional tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.15

      - name: Install k3s
        run: |
          set -eo pipefail
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install gomplate
        run: |
          go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest
          gomplate --version

      - name: Run functional tests
        timeout-minutes: 15
        run: |
          source devstack/openrc demo demo
          tools/functional_test.sh
