name: on push to main

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  unit_tests:
    uses: ./.github/workflows/tox.yaml
    with:
      ref: ${{ github.ref }}

  helm_lint:
    uses: ./.github/workflows/helm-lint.yaml
    with:
      ref: ${{ github.ref }}

  publish_images:
    needs: [unit_tests, helm_lint]
    uses: ./.github/workflows/publish-images.yaml
    permissions:
      contents: read
      id-token: write         # needed for signing the images with GitHub OIDC Token
      packages: write         # required for pushing container images
      security-events: write  # required for pushing SARIF files
    with:
      ref: ${{ github.ref }}

  publish_charts:
    permissions:
      contents: write
      id-token: none
      packages: none
      security-events: none
    needs: [publish_images]
    uses: ./.github/workflows/publish-charts.yaml
    with:
      ref: ${{ github.ref }}

  functional_tests:
    needs: [publish_images]
    with:
      ref: ${{ github.ref}}
    uses: ./.github/workflows/functional.yaml
