name: on tag

on:
  push:
    tags: ['**']

jobs:
  unit_tests:
    uses: ./.github/workflows/tox.yaml
    with:
      ref: ${{ github.ref }}

  publish_images:
    needs: [unit_tests]
    uses: ./.github/workflows/publish-images.yaml
    with:
      ref: ${{ github.ref }}

  publish_charts:
    needs: [publish_images]
    uses: ./.github/workflows/publish-charts.yaml
    with:
      ref: ${{ github.ref }}
